ecomapp/urls.py
from .views import *
from django.urls import path

app_name = "ecomapp"
urlpatterns = [
    path("",HomeView.as_view(),name="home"),
    path("about/",AboutView.as_view(),name="about"),
    path("contact-us/",ContactView.as_view(),name="Contact Us:-"),
    path("all-products/",AllProductView.as_view(),name="allproducts"),
    path("product/<slug:slug>/",ProductDetailView.as_view(),name="productdetail"),
    path("add-to-cart-<int:product_id>/",AddToCartView.as_view(),name="addtocart"),
    path("my-cart/",MyCartView.as_view(),name="mycart"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('ecomapp.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200,null=True)
    address = models.CharField(max_length=200,null=True,blank=True)
    joined_on = models.DateTimeField
    def __str__(self):
        return self.full_name


class Category (models.Model):
    title = models.CharField(max_length=200,null=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title=models.CharField(max_length=200,null=True)
    slug = models.SlugField(unique=True,null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to="products",null=True)
    marked_price = models.PositiveIntegerField(null=True)
    selling_price = models.PositiveIntegerField(null=True)
    description = models.TextField(null=True)
    warranty = models.CharField(max_length=300,null=True,blank=True)
    return_policy = models.CharField(max_length=300,null=True,blank=True)
    view_count = models.PositiveIntegerField(default=0,null=True)

    def __str__(self):
        return self.title


class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total= models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart:" +str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart" +str(self.cart.id) + "CartProduct: " + str(self.id)

ORDER_STATUS = (
    ("Order Received","Order Received"),
    ("Order Processing","Order Processing"),
    ("On the way","On the way"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled"),

)


class Order(models.Model):
    cart=models.OneToOneField(Cart,on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=50,null=True)
    shipping_address = models.CharField(max_length=300,null=True)
    mobile = models.CharField(max_length=10,null=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

ecomapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all().order_by("-id")
        context['categories'] = Category.objects.all()
        return context


class AllProductView(TemplateView):
    template_name = 'allproducts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ProductDetailView(TemplateView):
    template_name = "productdetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug=self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        product.view_count += 1
        product.save()
        context['product'] = product
        return context


class AddToCartView(TemplateView):
    template_name = "addtocart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #get product from requested url
        product_id = self.kwargs['product_id']
        #get product
        product_obj =Product.objects.get(id=product_id)
        #check if cart exists
        cart_id = self.request.session.get("cart_id",None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product=product_obj)
            
            #item already exists in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
            #new item is added in cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj,product=product_obj,rate=product_obj.selling_price,quantity=1,subtotal=product_obj.selling_price)
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
                
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id']=cart_obj.id
            cartproduct = CartProduct.objects.create(
                    cart=cart_obj,product=product_obj,rate=product_obj.selling_price,quantity=1,subtotal=product_obj.selling_price)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()
                

        return context
    


class MyCartView(TemplateView):
    template_name = "mycart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id",None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart =None
        context['cart'] = cart           
        return context
    


class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contactus.html'

ecomapp/templates/about.html
{% extends 'base.html' %}
{% block title %} About {% endblock %}
{% block content %}

    <h1>About Us</h1>

{% endblock %}

ecomapp/templates/addtocart.html
{% extends 'base.html' %}
{% block title %} Add To Cart {% endblock  %}

{% block content %}

<div class="container">
    <h3>Product Added Successfully!</h3>
</div>

{% endblock  %}

ecomapp/templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Products</h3>
    <hr>
    {% for results in categories %}
    <h4>{{results.title}}</h4>
    <div class="row">
        {% for result in results.product_set.all %}
<div class="col-lg-4 col-md-4 col-sm-6 col-12 ">
<div class="m-3">
    <img src="{{result.image.url}}" alt="" width="250px" height="250px">
    <h4> <a href="{% url 'ecomapp:productdetail' result.slug %}" style="text-decoration: none;">{{result.title}}</a> </h4>
    <p> <span style="font-size: 25px; color: #b12704;"> ₹{{result.selling_price}}</span>  <strike style="color: #555555;">₹{{result.marked_price}}</strike> </p>
    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a> 
</div>
</div>
{% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock  %}

ecomapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning ">
  <a class="navbar-brand" href="#" style="font-size: 30px;">The Bamboo Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active mr-2">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active mr-2">
        <a class="nav-link" href="/about/">About Us</a>
      </li>
      <li class="nav-item active mr-2">
        <a class="nav-link" href="/contact-us/">Contact Us</a>
      </li>
      <li class="nav-item active mr-2">
        <a class="nav-link" href="/all-products/">All Products</a>
      </li>
      <li class="nav-item active mr-2">
        <a class="nav-link" href="/my-cart/">Cart</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for results in categories %}
          <a class="dropdown-item" href="/all-products/">{{results.title}}</a>
          {% endfor %}
      </li>
     
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>
    

    {% block content %}
    {% endblock %}




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

ecomapp/templates/contactus.html
{% extends 'base.html' %}
{% block title %} Contact {% endblock %}

{% block content %}

    <h1>Contact Us</h1>

{% endblock %}

ecomapp/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}

{% block content %}

<body style="background-color: #eaeded;">
    


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.unsplash.com/photo-1577199019410-0d4567e04117?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1600&q=80&h=300" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1626519266242-a54bd74641a3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1600&q=80&h=300" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1504198453319-5ce911bafcde?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1600&q=80&h=300" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<br>
<div class="container" style="background-color: #ffffff;">
<div class="row  gallerys">
{% for result in products %}
<div class="col-lg-4 col-md-4 col-sm-6 col-12 ">
<div class="m-4">
    <img src="{{result.image.url}}" alt="" width="270px" height="270px">
    <h4> <a href="{% url 'ecomapp:productdetail' result.slug %}" style="text-decoration: none;">{{result.title}}</a> </h4>
    <p> <span style="font-size: 25px; color: #b12704;"> ₹{{result.selling_price}}</span>  <strike style="color: #555555;">₹{{result.marked_price}}</strike> </p>
    <!-- <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>  -->
</div>
</div>
{% endfor %}
</div> 
</div>
</body>
{% endblock %}

ecomapp/templates/mycart.html
{% extends 'base.html' %}

{% block title %} My Cart {% endblock  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <h4>Items in the cart</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>Sn</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for result in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{result.product.title}}</td>
                        <td>{{result.rate}}</td>
                        <td>{{result.quantity}}</td>
                        <td>{{result.subtotal}}</td>
                        <td>
                            <a href="" class="btn btn-primary">+</a>
                            <a href="" class="btn btn-warning">-</a>
                            <a href="" class="btn btn-danger">x</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th><b><span style=" color: #b12704;"> ₹{{cart.total}}</span></b></th>
                        <form><script src="https://checkout.razorpay.com/v1/payment-button.js" data-payment_button_id="pl_Jmb4hczBmoy1XA" data-prefill.total={{cart.total}} async> </script> </form>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock  %}

ecomapp/templates/productdetail.html
{% extends 'base.html' %}

{% block title %} {{product.title}} {% endblock  %}
 
{% block content%}

<div class="container" >
    <h3>Product: {{product.title}}</h3> <hr> <br>
    <div class="row"> 
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12"></div>
        <img src="{{product.image.url}}" alt="" class="img-fluid"  >
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12 ">
        <h4>{{product.title}} (viewed {{product.view_count}} times)</h4>
        <h5>Category: {{product.category}}</h5> <hr>
        <h5>  <span style="font-size: 25px; color: #b12704;"> ₹{{product.selling_price}}</span>  <strike style="color: #555555;">₹{{product.marked_price}}</strike>  </h5>
        <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-primary">Add To Cart</a><br><br>
        <span class="text-info">Warranty: {{product.warranty}}</span><br>
        <span class="text-info">Return Policy: {{product.return_policy}}</span>
            
        <p>{{product.description}}</p>
        
    </div>
    </div>
</div>

{% endblock  %}